const EmergencyApi = [
  {
    id: "1",
    name: "Dr.Uday Singh",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "2",
    name: "Dr.Kavv Pandey",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description:
      "A doctor is responsible for all sides of care of a patient.They diagnose, educate, and treat patients to ensure that they haveA doctor is responsible for all sides of care of a patient.They diagnose, educate, and treat patients to ensure that they haveA doctor is responsible for all sides of care of a patient.They diagnose, educate, and treat patients to ensure that they have",
    Address: "City Hospital",
  },
  {
    id: "3",
    name: "Dr.Devendra Rathore",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "4",
    name: "Arjun Patel",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "5",
    name: "Lalit Singh",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "6",
    name: "Dr. Ansh Joshi",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "7",
    name: "Arav roy",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
  {
    id: "8",
    name: "Arav roy",
    Icon: require("../../assets/doctor.png"),
    fees: "200",
    specialization: "Nurse",
    degree: "BSC Nursing",
    description: "djdjafiaheohfv",
    Address: "City Hospital",
  },
];
export default EmergencyApi;
