const NormalApi = [
  {
    id: "10",
    name: "Arav roy",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "20",
    name: "Ravi Dubey",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "30",
    name: "Tassu Tiwari",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "40",
    name: "Abhi Sharma",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "50",
    name: "Arav roy",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "60",
    name: "Arav roy",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "70",
    name: "Arav roy",
    Icon: require("../../assets/man.png"),
    fees: "200",
    degree: "Bsc",
    description: "fdnvnkfnoeuffcdjdci",
    work: "care taker",
  },
  {
    id: "80",
    name: "Arav roy",
    Icon: require("../../assets/man.png"),
    fees: "200",
    description: "fdnvnkfnoeuffcdjdci",
    degree: "Bsc",
    work: "care taker",
  },
];
export default NormalApi;
